# Generated by Django 4.1.1 on 2022-09-17 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User_Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assest_type_id', models.IntegerField()),
                ('assests_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_id', models.IntegerField()),
                ('bank_name', models.CharField(max_length=100)),
                ('acc_no', models.IntegerField()),
                ('acc_type', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type_id', models.IntegerField()),
                ('expense_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LiabilitesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liabilites_type_id', models.IntegerField()),
                ('liabilites_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.IntegerField(max_length=100000, primary_key=True, serialize=False)),
                ('transaction_date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('credit', models.FloatField()),
                ('debit', models.FloatField()),
                ('merchant', models.CharField(max_length=100)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transactions.bank')),
                ('expense_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transactions.expense')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='Liabilites',
            fields=[
                ('liablities_id', models.IntegerField(primary_key=True, serialize=False)),
                ('liablities_name', models.CharField(max_length=100)),
                ('uom', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('liablities_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transactions.liabilitestype')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Authentication.user')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transactions.expensetype'),
        ),
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_info_id', models.IntegerField()),
                ('recepient', models.EmailField(max_length=254)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transactions.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Assests',
            fields=[
                ('assest_id', models.IntegerField(primary_key=True, serialize=False)),
                ('assest_name', models.CharField(max_length=100)),
                ('uom', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('assest_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transactions.assesttype')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Authentication.user')),
            ],
        ),
    ]
