# Generated by Django 4.1.1 on 2022-09-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
